#!/bin/bash

set -euxo pipefail

setsebool -P container_manage_cgroup true

if ! /usr/bin/podman volume exists microshift-data
then
  /usr/bin/podman volume create microshift-data
fi

[[ -d /etc/microshift-containerized ]] || mkdir -p /etc/microshift-containerized
cat <<EOF > /etc/microshift-containerized/microshift-containerized.conf
export KUBECONFIG=$(/usr/bin/podman volume inspect microshift-data --format "{{.Mountpoint}}")/microshift/resources/kubeadmin/kubeconfig
EOF
